language: php
php:
- '5.6'
- '7'
- '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE ci;'
  - mysql -e 'SELECT ci;'
  - mysql -e 'CREATE TABLE users (user VARCHAR(32) NOT NULL, hash VARCHAR(255) NOT NULL)'

install: composer install

script: vendor/bin/phpunit
